services:
  media-downloader:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    image: ghcr.io/markuskreitzer/media-downloader:latest
    container_name: media-downloader
    ports:
      - "8001:8001"
    volumes:
      - ../Incoming:/.downloads
      - ./download_errors.log:/app/download_errors.log
    environment:
      - DOWNLOAD_DIR=/.downloads
      # Uncomment and set these for Plex integration
      # - PLEX_URL=http://plex-server:32400
      # - PLEX_TOKEN=your_plex_token
      # - PLEX_LIBRARY=Memes
    restart: unless-stopped
    # If you need to connect to a local Plex server on the same machine
    # Uncomment the following lines:
    # network_mode: "host"
