services:
  media-downloader:
    platform: linux/amd64
    image: ghcr.io/markuskreitzer/media_downloader:master
    pull_policy: always
    container_name: media-downloader
    ports:
      - "8001:8000"
    volumes:
      - /volume2/Media/Incoming:/downloads
      - ./download_errors.log:/app/download_errors.log
    env_file:
      - .env
    environment:
      - DOWNLOAD_DIR=/downloads
      - RABBITMQ_REQUIRED=true
      # Environment variables here override those in .env file
      # Uncomment and set these for Plex integration
      # - PLEX_URL=http://plex-server:32400
      # - PLEX_TOKEN=your_plex_token
      # - PLEX_LIBRARY=Memes
    restart: unless-stopped
    # If you need to connect to a local Plex server on the same machine
    # Uncomment the following lines:
    # network_mode: "host"
